/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 73
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 1
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_POUNDcdl = 2,
  anon_sym_COLON = 3,
  sym_comment = 4,
  anon_sym_COMMA = 5,
  anon_sym_mprt = 6,
  anon_sym_masm = 7,
  anon_sym_mdrw = 8,
  anon_sym_easm = 9,
  anon_sym_do = 10,
  anon_sym_end = 11,
  anon_sym_PIPE = 12,
  anon_sym_config = 13,
  anon_sym_configuration = 14,
  anon_sym_dep = 15,
  anon_sym_depends_on = 16,
  anon_sym_content = 17,
  anon_sym_content_generate = 18,
  anon_sym_metadata = 19,
  anon_sym_meta = 20,
  anon_sym_drawing_of = 21,
  anon_sym_active = 22,
  anon_sym_true = 23,
  anon_sym_false = 24,
  sym_integer = 25,
  anon_sym_DQUOTE = 26,
  sym_string_content = 27,
  sym_escape_sequence = 28,
  anon_sym_POUND_LBRACE = 29,
  aux_sym_interpolation_token1 = 30,
  anon_sym_RBRACE = 31,
  sym_source_file = 32,
  sym_version_directive = 33,
  sym_file_definition = 34,
  sym_file_type = 35,
  sym_block = 36,
  sym_block_params = 37,
  sym_property_call = 38,
  sym_property_keyword = 39,
  sym_keyword_arg = 40,
  sym_boolean = 41,
  sym_string = 42,
  sym_interpolation = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_block_repeat1 = 45,
  aux_sym_block_params_repeat1 = 46,
  aux_sym_property_call_repeat1 = 47,
  aux_sym_string_repeat1 = 48,
  alias_sym_keyword_arg_name = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_POUNDcdl] = "#cdl",
  [anon_sym_COLON] = ":",
  [sym_comment] = "comment",
  [anon_sym_COMMA] = ",",
  [anon_sym_mprt] = "mprt",
  [anon_sym_masm] = "masm",
  [anon_sym_mdrw] = "mdrw",
  [anon_sym_easm] = "easm",
  [anon_sym_do] = "do",
  [anon_sym_end] = "end",
  [anon_sym_PIPE] = "|",
  [anon_sym_config] = "config",
  [anon_sym_configuration] = "configuration",
  [anon_sym_dep] = "dep",
  [anon_sym_depends_on] = "depends_on",
  [anon_sym_content] = "content",
  [anon_sym_content_generate] = "content_generate",
  [anon_sym_metadata] = "metadata",
  [anon_sym_meta] = "meta",
  [anon_sym_drawing_of] = "drawing_of",
  [anon_sym_active] = "active",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_integer] = "integer",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_POUND_LBRACE] = "#{",
  [aux_sym_interpolation_token1] = "interpolation_token1",
  [anon_sym_RBRACE] = "}",
  [sym_source_file] = "source_file",
  [sym_version_directive] = "version_directive",
  [sym_file_definition] = "file_definition",
  [sym_file_type] = "file_type",
  [sym_block] = "block",
  [sym_block_params] = "block_params",
  [sym_property_call] = "property_call",
  [sym_property_keyword] = "property_keyword",
  [sym_keyword_arg] = "keyword_arg",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym_interpolation] = "interpolation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_block_params_repeat1] = "block_params_repeat1",
  [aux_sym_property_call_repeat1] = "property_call_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [alias_sym_keyword_arg_name] = "keyword_arg_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_POUNDcdl] = anon_sym_POUNDcdl,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_comment] = sym_comment,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_mprt] = anon_sym_mprt,
  [anon_sym_masm] = anon_sym_masm,
  [anon_sym_mdrw] = anon_sym_mdrw,
  [anon_sym_easm] = anon_sym_easm,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_config] = anon_sym_config,
  [anon_sym_configuration] = anon_sym_configuration,
  [anon_sym_dep] = anon_sym_dep,
  [anon_sym_depends_on] = anon_sym_depends_on,
  [anon_sym_content] = anon_sym_content,
  [anon_sym_content_generate] = anon_sym_content_generate,
  [anon_sym_metadata] = anon_sym_metadata,
  [anon_sym_meta] = anon_sym_meta,
  [anon_sym_drawing_of] = anon_sym_drawing_of,
  [anon_sym_active] = anon_sym_active,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_integer] = sym_integer,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_POUND_LBRACE] = anon_sym_POUND_LBRACE,
  [aux_sym_interpolation_token1] = aux_sym_interpolation_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_source_file] = sym_source_file,
  [sym_version_directive] = sym_version_directive,
  [sym_file_definition] = sym_file_definition,
  [sym_file_type] = sym_file_type,
  [sym_block] = sym_block,
  [sym_block_params] = sym_block_params,
  [sym_property_call] = sym_property_call,
  [sym_property_keyword] = sym_property_keyword,
  [sym_keyword_arg] = sym_keyword_arg,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym_interpolation] = sym_interpolation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_block_params_repeat1] = aux_sym_block_params_repeat1,
  [aux_sym_property_call_repeat1] = aux_sym_property_call_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [alias_sym_keyword_arg_name] = alias_sym_keyword_arg_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUNDcdl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mprt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_masm] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mdrw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_easm] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_config] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_configuration] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dep] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_depends_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_content] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_content_generate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_metadata] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_meta] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_drawing_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_active] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_interpolation_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_version_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_file_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_file_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_params] = {
    .visible = true,
    .named = true,
  },
  [sym_property_call] = {
    .visible = true,
    .named = true,
  },
  [sym_property_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_property_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_keyword_arg_name] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_keyword_arg_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 8,
  [11] = 6,
  [12] = 7,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 17,
  [40] = 21,
  [41] = 41,
  [42] = 22,
  [43] = 24,
  [44] = 44,
  [45] = 45,
  [46] = 25,
  [47] = 47,
  [48] = 29,
  [49] = 49,
  [50] = 33,
  [51] = 51,
  [52] = 47,
  [53] = 49,
  [54] = 34,
  [55] = 31,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 58,
  [63] = 60,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 18,
        '#', 10,
        ',', 15,
        '/', 2,
        ':', 9,
        '\\', 4,
        '|', 16,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == '\\') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == '{') ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 5:
      if (eof) ADVANCE(7);
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == ',') ADVANCE(15);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '|') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_POUNDcdl);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'c') ADVANCE(12);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'c') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'd') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'l') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_string_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'd') ADVANCE(3);
      if (lookahead == 'e') ADVANCE(4);
      if (lookahead == 'f') ADVANCE(5);
      if (lookahead == 'm') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'c') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(10);
      if (lookahead == 'o') ADVANCE(11);
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead == 'd') ADVANCE(17);
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(34);
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_dep);
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 24:
      if (lookahead == 'w') ADVANCE(37);
      END_STATE();
    case 25:
      if (lookahead == 'm') ADVANCE(38);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 28:
      if (lookahead == 'm') ADVANCE(40);
      END_STATE();
    case 29:
      if (lookahead == 'w') ADVANCE(41);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(42);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 33:
      if (lookahead == 'v') ADVANCE(45);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(46);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_easm);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_masm);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_mdrw);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_meta);
      if (lookahead == 'd') ADVANCE(51);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_mprt);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 46:
      if (lookahead == 'g') ADVANCE(53);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 48:
      if (lookahead == 'd') ADVANCE(55);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 51:
      if (lookahead == 'a') ADVANCE(57);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_active);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_config);
      if (lookahead == 'u') ADVANCE(58);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 55:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 56:
      if (lookahead == 'g') ADVANCE(61);
      END_STATE();
    case 57:
      if (lookahead == 't') ADVANCE(62);
      END_STATE();
    case 58:
      if (lookahead == 'r') ADVANCE(63);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_content);
      if (lookahead == '_') ADVANCE(64);
      END_STATE();
    case 60:
      if (lookahead == '_') ADVANCE(65);
      END_STATE();
    case 61:
      if (lookahead == '_') ADVANCE(66);
      END_STATE();
    case 62:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 63:
      if (lookahead == 'a') ADVANCE(68);
      END_STATE();
    case 64:
      if (lookahead == 'g') ADVANCE(69);
      END_STATE();
    case 65:
      if (lookahead == 'o') ADVANCE(70);
      END_STATE();
    case 66:
      if (lookahead == 'o') ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_metadata);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 69:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 70:
      if (lookahead == 'n') ADVANCE(74);
      END_STATE();
    case 71:
      if (lookahead == 'f') ADVANCE(75);
      END_STATE();
    case 72:
      if (lookahead == 'i') ADVANCE(76);
      END_STATE();
    case 73:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_depends_on);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_drawing_of);
      END_STATE();
    case 76:
      if (lookahead == 'o') ADVANCE(78);
      END_STATE();
    case 77:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(81);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_configuration);
      END_STATE();
    case 81:
      if (lookahead == 'a') ADVANCE(82);
      END_STATE();
    case 82:
      if (lookahead == 't') ADVANCE(83);
      END_STATE();
    case 83:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_content_generate);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 5},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 23},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_POUNDcdl] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_mprt] = ACTIONS(1),
    [anon_sym_masm] = ACTIONS(1),
    [anon_sym_mdrw] = ACTIONS(1),
    [anon_sym_easm] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_config] = ACTIONS(1),
    [anon_sym_configuration] = ACTIONS(1),
    [anon_sym_dep] = ACTIONS(1),
    [anon_sym_depends_on] = ACTIONS(1),
    [anon_sym_content] = ACTIONS(1),
    [anon_sym_content_generate] = ACTIONS(1),
    [anon_sym_metadata] = ACTIONS(1),
    [anon_sym_meta] = ACTIONS(1),
    [anon_sym_drawing_of] = ACTIONS(1),
    [anon_sym_active] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_POUND_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(66),
    [sym_version_directive] = STATE(35),
    [sym_file_definition] = STATE(38),
    [sym_file_type] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(38),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUNDcdl] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [anon_sym_mprt] = ACTIONS(9),
    [anon_sym_masm] = ACTIONS(9),
    [anon_sym_mdrw] = ACTIONS(9),
    [anon_sym_easm] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_block] = STATE(26),
    [sym_boolean] = STATE(13),
    [sym_string] = STATE(13),
    [aux_sym_property_call_repeat1] = STATE(14),
    [sym_identifier] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_mprt] = ACTIONS(17),
    [anon_sym_masm] = ACTIONS(17),
    [anon_sym_mdrw] = ACTIONS(17),
    [anon_sym_easm] = ACTIONS(17),
    [anon_sym_do] = ACTIONS(19),
    [anon_sym_end] = ACTIONS(17),
    [anon_sym_config] = ACTIONS(17),
    [anon_sym_configuration] = ACTIONS(17),
    [anon_sym_dep] = ACTIONS(17),
    [anon_sym_depends_on] = ACTIONS(17),
    [anon_sym_content] = ACTIONS(17),
    [anon_sym_content_generate] = ACTIONS(17),
    [anon_sym_metadata] = ACTIONS(17),
    [anon_sym_meta] = ACTIONS(17),
    [anon_sym_drawing_of] = ACTIONS(17),
    [anon_sym_active] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_integer] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(27), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_end,
    ACTIONS(31), 1,
      anon_sym_PIPE,
    STATE(2), 1,
      sym_property_keyword,
    STATE(6), 1,
      sym_block_params,
    STATE(63), 1,
      sym_file_type,
    STATE(7), 3,
      sym_file_definition,
      sym_property_call,
      aux_sym_block_repeat1,
    ACTIONS(9), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
    ACTIONS(33), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(35), 6,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [44] = 2,
    ACTIONS(39), 4,
      sym_comment,
      anon_sym_COMMA,
      sym_integer,
      anon_sym_DQUOTE,
    ACTIONS(37), 19,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_do,
      anon_sym_end,
      anon_sym_config,
      anon_sym_configuration,
      anon_sym_dep,
      anon_sym_depends_on,
      anon_sym_content,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_meta,
      anon_sym_drawing_of,
      anon_sym_active,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [72] = 10,
    ACTIONS(31), 1,
      anon_sym_PIPE,
    ACTIONS(41), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_end,
    STATE(2), 1,
      sym_property_keyword,
    STATE(11), 1,
      sym_block_params,
    STATE(63), 1,
      sym_file_type,
    STATE(12), 3,
      sym_file_definition,
      sym_property_call,
      aux_sym_block_repeat1,
    ACTIONS(9), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
    ACTIONS(33), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(35), 6,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [116] = 8,
    ACTIONS(45), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_end,
    STATE(2), 1,
      sym_property_keyword,
    STATE(63), 1,
      sym_file_type,
    STATE(8), 3,
      sym_file_definition,
      sym_property_call,
      aux_sym_block_repeat1,
    ACTIONS(9), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
    ACTIONS(33), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(35), 6,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [154] = 8,
    ACTIONS(47), 1,
      anon_sym_end,
    ACTIONS(49), 1,
      sym_comment,
    STATE(2), 1,
      sym_property_keyword,
    STATE(63), 1,
      sym_file_type,
    STATE(9), 3,
      sym_file_definition,
      sym_property_call,
      aux_sym_block_repeat1,
    ACTIONS(9), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
    ACTIONS(33), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(35), 6,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [192] = 8,
    ACTIONS(49), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_end,
    STATE(2), 1,
      sym_property_keyword,
    STATE(63), 1,
      sym_file_type,
    STATE(9), 3,
      sym_file_definition,
      sym_property_call,
      aux_sym_block_repeat1,
    ACTIONS(9), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
    ACTIONS(33), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(35), 6,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [230] = 8,
    ACTIONS(53), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_end,
    STATE(2), 1,
      sym_property_keyword,
    STATE(63), 1,
      sym_file_type,
    STATE(9), 3,
      sym_file_definition,
      sym_property_call,
      aux_sym_block_repeat1,
    ACTIONS(56), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
    ACTIONS(61), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(64), 6,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [268] = 8,
    ACTIONS(49), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_end,
    STATE(2), 1,
      sym_property_keyword,
    STATE(63), 1,
      sym_file_type,
    STATE(9), 3,
      sym_file_definition,
      sym_property_call,
      aux_sym_block_repeat1,
    ACTIONS(9), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
    ACTIONS(33), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(35), 6,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [306] = 8,
    ACTIONS(69), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_end,
    STATE(2), 1,
      sym_property_keyword,
    STATE(63), 1,
      sym_file_type,
    STATE(10), 3,
      sym_file_definition,
      sym_property_call,
      aux_sym_block_repeat1,
    ACTIONS(9), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
    ACTIONS(33), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(35), 6,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [344] = 8,
    ACTIONS(49), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_end,
    STATE(2), 1,
      sym_property_keyword,
    STATE(63), 1,
      sym_file_type,
    STATE(9), 3,
      sym_file_definition,
      sym_property_call,
      aux_sym_block_repeat1,
    ACTIONS(9), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
    ACTIONS(33), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(35), 6,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [382] = 6,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    ACTIONS(75), 1,
      anon_sym_do,
    STATE(15), 1,
      aux_sym_property_call_repeat1,
    STATE(28), 1,
      sym_block,
    ACTIONS(77), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(73), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [415] = 6,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    ACTIONS(75), 1,
      anon_sym_do,
    STATE(18), 1,
      aux_sym_property_call_repeat1,
    STATE(28), 1,
      sym_block,
    ACTIONS(77), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(73), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [448] = 6,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    ACTIONS(75), 1,
      anon_sym_do,
    STATE(18), 1,
      aux_sym_property_call_repeat1,
    STATE(32), 1,
      sym_block,
    ACTIONS(81), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(79), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [481] = 3,
    ACTIONS(83), 1,
      anon_sym_COLON,
    ACTIONS(87), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(85), 14,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_do,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [507] = 5,
    ACTIONS(75), 1,
      anon_sym_do,
    ACTIONS(91), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      sym_block,
    ACTIONS(93), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(89), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [537] = 4,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    STATE(18), 1,
      aux_sym_property_call_repeat1,
    ACTIONS(87), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(85), 13,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_do,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [565] = 2,
    ACTIONS(100), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(98), 14,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_do,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [588] = 2,
    ACTIONS(87), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(85), 14,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_do,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [611] = 4,
    ACTIONS(75), 1,
      anon_sym_do,
    STATE(29), 1,
      sym_block,
    ACTIONS(104), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(102), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [638] = 2,
    ACTIONS(108), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(106), 14,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_do,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [661] = 2,
    ACTIONS(112), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(110), 14,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_do,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [684] = 2,
    ACTIONS(116), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(114), 14,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_do,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [707] = 2,
    ACTIONS(120), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(118), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [728] = 2,
    ACTIONS(77), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(73), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [749] = 2,
    ACTIONS(124), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(122), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [770] = 2,
    ACTIONS(81), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(79), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [791] = 2,
    ACTIONS(128), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(126), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [812] = 2,
    ACTIONS(132), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(130), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [833] = 2,
    ACTIONS(136), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(134), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [854] = 2,
    ACTIONS(140), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(138), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [875] = 2,
    ACTIONS(144), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(142), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [896] = 2,
    ACTIONS(148), 4,
      anon_sym_config,
      anon_sym_dep,
      anon_sym_content,
      anon_sym_meta,
    ACTIONS(146), 12,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_end,
      anon_sym_configuration,
      anon_sym_depends_on,
      anon_sym_content_generate,
      anon_sym_metadata,
      anon_sym_drawing_of,
      anon_sym_active,
  [917] = 5,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(152), 1,
      sym_comment,
    STATE(60), 1,
      sym_file_type,
    STATE(37), 2,
      sym_file_definition,
      aux_sym_source_file_repeat1,
    ACTIONS(9), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
  [937] = 5,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 1,
      sym_comment,
    STATE(60), 1,
      sym_file_type,
    STATE(36), 2,
      sym_file_definition,
      aux_sym_source_file_repeat1,
    ACTIONS(159), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
  [957] = 5,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
    ACTIONS(164), 1,
      sym_comment,
    STATE(60), 1,
      sym_file_type,
    STATE(36), 2,
      sym_file_definition,
      aux_sym_source_file_repeat1,
    ACTIONS(9), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
  [977] = 5,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(164), 1,
      sym_comment,
    STATE(60), 1,
      sym_file_type,
    STATE(36), 2,
      sym_file_definition,
      aux_sym_source_file_repeat1,
    ACTIONS(9), 4,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
  [997] = 4,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_do,
    STATE(50), 1,
      sym_block,
    ACTIONS(89), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
  [1015] = 3,
    ACTIONS(168), 1,
      anon_sym_do,
    STATE(48), 1,
      sym_block,
    ACTIONS(102), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
  [1030] = 5,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(170), 1,
      sym_identifier,
    ACTIONS(172), 1,
      sym_integer,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 3,
      sym_keyword_arg,
      sym_boolean,
      sym_string,
  [1049] = 1,
    ACTIONS(106), 8,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_do,
  [1060] = 1,
    ACTIONS(114), 8,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_COMMA,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
      anon_sym_do,
  [1071] = 5,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(176), 1,
      sym_integer,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(23), 2,
      sym_boolean,
      sym_string,
  [1089] = 1,
    ACTIONS(178), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
  [1098] = 1,
    ACTIONS(118), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
  [1107] = 5,
    ACTIONS(180), 1,
      anon_sym_DQUOTE,
    ACTIONS(182), 1,
      sym_string_content,
    ACTIONS(184), 1,
      sym_escape_sequence,
    ACTIONS(186), 1,
      anon_sym_POUND_LBRACE,
    STATE(49), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1124] = 1,
    ACTIONS(126), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
  [1133] = 5,
    ACTIONS(186), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(188), 1,
      anon_sym_DQUOTE,
    ACTIONS(190), 1,
      sym_string_content,
    ACTIONS(192), 1,
      sym_escape_sequence,
    STATE(51), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1150] = 1,
    ACTIONS(142), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
  [1159] = 5,
    ACTIONS(194), 1,
      anon_sym_DQUOTE,
    ACTIONS(196), 1,
      sym_string_content,
    ACTIONS(199), 1,
      sym_escape_sequence,
    ACTIONS(202), 1,
      anon_sym_POUND_LBRACE,
    STATE(51), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1176] = 5,
    ACTIONS(186), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    ACTIONS(207), 1,
      sym_string_content,
    ACTIONS(209), 1,
      sym_escape_sequence,
    STATE(53), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1193] = 5,
    ACTIONS(186), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(190), 1,
      sym_string_content,
    ACTIONS(192), 1,
      sym_escape_sequence,
    ACTIONS(211), 1,
      anon_sym_DQUOTE,
    STATE(51), 2,
      sym_interpolation,
      aux_sym_string_repeat1,
  [1210] = 1,
    ACTIONS(146), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
  [1219] = 1,
    ACTIONS(134), 6,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_mprt,
      anon_sym_masm,
      anon_sym_mdrw,
      anon_sym_easm,
  [1228] = 2,
    ACTIONS(215), 1,
      sym_string_content,
    ACTIONS(213), 3,
      anon_sym_DQUOTE,
      sym_escape_sequence,
      anon_sym_POUND_LBRACE,
  [1237] = 3,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_PIPE,
    STATE(61), 1,
      aux_sym_block_params_repeat1,
  [1247] = 3,
    ACTIONS(221), 1,
      sym_identifier,
    ACTIONS(223), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      sym_string,
  [1257] = 3,
    ACTIONS(225), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_PIPE,
    STATE(59), 1,
      aux_sym_block_params_repeat1,
  [1267] = 3,
    ACTIONS(223), 1,
      anon_sym_DQUOTE,
    ACTIONS(230), 1,
      sym_identifier,
    STATE(39), 1,
      sym_string,
  [1277] = 3,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_PIPE,
    STATE(59), 1,
      aux_sym_block_params_repeat1,
  [1287] = 3,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(234), 1,
      sym_identifier,
    STATE(21), 1,
      sym_string,
  [1297] = 3,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(236), 1,
      sym_identifier,
    STATE(17), 1,
      sym_string,
  [1307] = 1,
    ACTIONS(228), 2,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1312] = 1,
    ACTIONS(238), 2,
      anon_sym_DQUOTE,
      sym_identifier,
  [1317] = 1,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
  [1321] = 1,
    ACTIONS(242), 1,
      aux_sym_interpolation_token1,
  [1325] = 1,
    ACTIONS(244), 1,
      sym_integer,
  [1329] = 1,
    ACTIONS(246), 1,
      anon_sym_COLON,
  [1333] = 1,
    ACTIONS(248), 1,
      sym_identifier,
  [1337] = 1,
    ACTIONS(250), 1,
      anon_sym_RBRACE,
  [1341] = 1,
    ACTIONS(252), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 72,
  [SMALL_STATE(6)] = 116,
  [SMALL_STATE(7)] = 154,
  [SMALL_STATE(8)] = 192,
  [SMALL_STATE(9)] = 230,
  [SMALL_STATE(10)] = 268,
  [SMALL_STATE(11)] = 306,
  [SMALL_STATE(12)] = 344,
  [SMALL_STATE(13)] = 382,
  [SMALL_STATE(14)] = 415,
  [SMALL_STATE(15)] = 448,
  [SMALL_STATE(16)] = 481,
  [SMALL_STATE(17)] = 507,
  [SMALL_STATE(18)] = 537,
  [SMALL_STATE(19)] = 565,
  [SMALL_STATE(20)] = 588,
  [SMALL_STATE(21)] = 611,
  [SMALL_STATE(22)] = 638,
  [SMALL_STATE(23)] = 661,
  [SMALL_STATE(24)] = 684,
  [SMALL_STATE(25)] = 707,
  [SMALL_STATE(26)] = 728,
  [SMALL_STATE(27)] = 749,
  [SMALL_STATE(28)] = 770,
  [SMALL_STATE(29)] = 791,
  [SMALL_STATE(30)] = 812,
  [SMALL_STATE(31)] = 833,
  [SMALL_STATE(32)] = 854,
  [SMALL_STATE(33)] = 875,
  [SMALL_STATE(34)] = 896,
  [SMALL_STATE(35)] = 917,
  [SMALL_STATE(36)] = 937,
  [SMALL_STATE(37)] = 957,
  [SMALL_STATE(38)] = 977,
  [SMALL_STATE(39)] = 997,
  [SMALL_STATE(40)] = 1015,
  [SMALL_STATE(41)] = 1030,
  [SMALL_STATE(42)] = 1049,
  [SMALL_STATE(43)] = 1060,
  [SMALL_STATE(44)] = 1071,
  [SMALL_STATE(45)] = 1089,
  [SMALL_STATE(46)] = 1098,
  [SMALL_STATE(47)] = 1107,
  [SMALL_STATE(48)] = 1124,
  [SMALL_STATE(49)] = 1133,
  [SMALL_STATE(50)] = 1150,
  [SMALL_STATE(51)] = 1159,
  [SMALL_STATE(52)] = 1176,
  [SMALL_STATE(53)] = 1193,
  [SMALL_STATE(54)] = 1210,
  [SMALL_STATE(55)] = 1219,
  [SMALL_STATE(56)] = 1228,
  [SMALL_STATE(57)] = 1237,
  [SMALL_STATE(58)] = 1247,
  [SMALL_STATE(59)] = 1257,
  [SMALL_STATE(60)] = 1267,
  [SMALL_STATE(61)] = 1277,
  [SMALL_STATE(62)] = 1287,
  [SMALL_STATE(63)] = 1297,
  [SMALL_STATE(64)] = 1307,
  [SMALL_STATE(65)] = 1312,
  [SMALL_STATE(66)] = 1317,
  [SMALL_STATE(67)] = 1321,
  [SMALL_STATE(68)] = 1325,
  [SMALL_STATE(69)] = 1329,
  [SMALL_STATE(70)] = 1333,
  [SMALL_STATE(71)] = 1337,
  [SMALL_STATE(72)] = 1341,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_call, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_call, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_keyword, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_keyword, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_call, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_call, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_call, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_call, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_property_call_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_property_call_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_definition, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_definition, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_property_call_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_definition, 4, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_definition, 4, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword_arg, 3, 0, 1),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword_arg, 3, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_params, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_params, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_definition, 5, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_definition, 5, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_params, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_params, 4, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_call, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_call, 4, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_definition, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_definition, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version_directive, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [199] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [202] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_params_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_params_repeat1, 2, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_type, 1, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cg(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cg",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
